server:
  port: 8000

spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:postgresql://localhost:55432/url_shortener?options=-c%20TimeZone=Asia/Kolkata
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379